openapi: '3.1.1'
info:
  title: SStatic | v1
  description: "SStatic is a simple static file and link shortener server.\n\n## Authentication\nSome endpoints require authentication. SStatic is configured to use OpenID Connect (OIDC) for authentication.\nYou can obtain a JWT bearer token from your OIDC provider and include it in the `Authorization` header of your requests.\n\nYou can use [OAuth 2.0 Playground](https://oauthlabs.com/) to obtain a JWT token from your identity provider.\n\nJWT tokens are used only for testing or automation purposes. For regular usage, SStatic uses cookie-based authentication with OIDC."
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
  version: 1.0.0
  summary: API documentation for SStatic server.
servers:
  - url: http://localhost:5141/
paths:
  /_/auth/user:
    get:
      tags:
        - Auth
      summary: Get user information
      description: Retrieve information about the authenticated user.
      operationId: GetUserInfo
      responses:
        '200':
          description: User information retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetUserResponse'
  /_/auth/login:
    get:
      tags:
        - Auth
      summary: Login
      description: Initiate the login process. See OpenID specification for more details.
      operationId: Login
      parameters:
        - name: redirect
          in: query
          description: The redirect URI after login.
          schema:
            type: string
      responses:
        '200':
          description: OK
    post:
      tags:
        - Auth
      summary: Log in using password
      description: "Authenticate user using login/password pair.\nOnly cookie-base authentication is available for this method.\nThis endpoint is available only if administrator has enabled it."
      operationId: PasswordLogin
      requestBody:
        description: Login request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
        required: true
      responses:
        '400':
          description: Incorrect username or password.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: One or more validation errors occured.
                status: 400
                detail: string
                errors:
                  field:string:
                    - error:string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '200':
          description: User successfully logged in.
  /_/auth/oidc-signin:
    post:
      tags:
        - Auth
      summary: OpenID Connect callback
      description: Handle the OpenID Connect callback after authentication. See OpenID specification for more details.
      operationId: OidcCallback
      responses:
        '400':
          description: Invalid callback.
  /_/auth/oidc-logout:
    get:
      tags:
        - Auth
      summary: OpenID Connect logout callback
      description: Handle the OpenID Connect logout callback after signing out. See OpenID specification for more details.
      operationId: OidcLogoutCallback
      responses:
        '400':
          description: Invalid callback.
  /_/auth/logout:
    get:
      tags:
        - Auth
      summary: Logout
      description: Initiate the logout process. See OpenID specification for more details.
      operationId: Logout
      parameters:
        - name: redirect
          in: query
          description: The redirect URL after logout. Must be a relative URL
          schema:
            type: string
      responses:
        '200':
          description: OK
  /_/api/healthz:
    get:
      tags:
        - Public
      summary: Health check
      description: Check the health of the application.
      operationId: Health
      responses:
        '200':
          description: Application is healthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
        '503':
          description: Application is unhealthy.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
  /_/api/info:
    get:
      tags:
        - Public
      summary: Get runtime information
      description: Retrieve runtime information about the application.
      operationId: GetInfo
      responses:
        '200':
          description: Runtime information retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetRuntimeInfoResponse'
  /_/api/links:
    get:
      tags:
        - Links
      summary: List links
      description: Retrieve all short links.
      operationId: ListLinks
      parameters:
        - name: Tags
          in: query
          description: An optional array of tag IDs to filter the links.
          schema:
            type: array
            items:
              pattern: '^-?(?:0|[1-9]\d*)$'
              type:
                - integer
                - string
              format: int32
        - name: Enabled
          in: query
          description: An optional boolean to filter links by their state (enabled/disabled).
          schema:
            type: boolean
      responses:
        '200':
          description: Links retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ShortLink'
        '400':
          description: One or more validation errors occurred.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: One or more validation errors occured.
                status: 400
                detail: string
                errors:
                  field:string:
                    - error:string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    post:
      tags:
        - Links
      summary: Create link
      description: 'Create a new link by its slug. If the link contains tags that do not exist, they will be created.'
      operationId: CreateLink
      requestBody:
        description: The link data.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLinkRequest'
        required: true
      responses:
        '201':
          description: Link created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortLink'
        '400':
          description: One or more validation errors occurred.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: One or more validation errors occured.
                status: 400
                detail: string
                errors:
                  field:string:
                    - error:string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
  '/_/api/links/{slug}':
    get:
      tags:
        - Links
      summary: Get link
      description: Retrieve a link by its slug.
      operationId: GetLink
      parameters:
        - name: slug
          in: path
          description: The slug of the link to retrieve.
          required: true
          schema:
            pattern: '[a-zA-Z0-9-_.]+'
            type: string
      responses:
        '200':
          description: Link retrieved successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortLink'
        '404':
          description: Link not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    post:
      tags:
        - Links
      summary: Update link
      description: 'Update or create a link by its slug. If the link contains tags that do not exist, they will be created.'
      operationId: UpdateLink
      parameters:
        - name: slug
          in: path
          description: The slug of the link to update.
          required: true
          schema:
            pattern: '[a-zA-Z0-9-_.]+'
            type: string
      requestBody:
        description: The updated link data.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateLinkRequest'
        required: true
      responses:
        '200':
          description: Link updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShortLink'
        '404':
          description: Link not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '400':
          description: One or more validation errors occurred.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: One or more validation errors occured.
                status: 400
                detail: string
                errors:
                  field:string:
                    - error:string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    delete:
      tags:
        - Links
      summary: Delete link
      description: Delete a link by its slug.
      operationId: DeleteLink
      parameters:
        - name: slug
          in: path
          description: The slug of the link to delete.
          required: true
          schema:
            pattern: '[a-zA-Z0-9-_.]+'
            type: string
      responses:
        '204':
          description: Link deleted successfully.
        '404':
          description: Link not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
  /_/api/tags:
    get:
      tags:
        - Tags
      summary: List all tags
      description: Retrieve a list of all tags.
      operationId: ListTags
      responses:
        '200':
          description: List of tags retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tag'
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    post:
      tags:
        - Tags
      summary: Create tag
      description: Create a new tag.
      operationId: CreateTag
      requestBody:
        description: The tag data to create.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTagRequest'
        required: true
      responses:
        '201':
          description: Tag created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          description: One or more validation errors occurred.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: One or more validation errors occured.
                status: 400
                detail: string
                errors:
                  field:string:
                    - error:string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
  '/_/api/tags/{id}':
    get:
      tags:
        - Tags
      summary: Get tag
      description: Retrieve a tag by its ID.
      operationId: GetTag
      parameters:
        - name: id
          in: path
          description: The ID of the tag to retrieve.
          required: true
          schema:
            pattern: '^-?(?:0|[1-9]\d*)$'
            type: integer
            format: int32
      responses:
        '200':
          description: Tag found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '404':
          description: Tag not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    put:
      tags:
        - Tags
      summary: Update tag
      description: Update an existing tag.
      operationId: UpdateTag
      parameters:
        - name: id
          in: path
          description: The ID of the tag to update.
          required: true
          schema:
            pattern: '^-?(?:0|[1-9]\d*)$'
            type: integer
            format: int32
      requestBody:
        description: The updated tag data.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTagRequest'
        required: true
      responses:
        '200':
          description: Tag updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '201':
          description: Tag with specified ID was created.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tag'
        '400':
          description: One or more validation errors occurred.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: One or more validation errors occured.
                status: 400
                detail: string
                errors:
                  field:string:
                    - error:string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    delete:
      tags:
        - Tags
      summary: Delete tag
      description: Delete a tag by its ID.
      operationId: DeleteTag
      parameters:
        - name: id
          in: path
          description: The ID of the tag to delete.
          required: true
          schema:
            pattern: '^-?(?:0|[1-9]\d*)$'
            type: integer
            format: int32
      responses:
        '204':
          description: Tag deleted successfully.
        '404':
          description: Tag not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
  '/_/api/files/{path}':
    get:
      tags:
        - Files
      summary: Get file or directory information
      description: Retrieve information about a file or directory on the specified path.
      operationId: GetFileInfo
      parameters:
        - name: path
          in: path
          description: The path of the file or directory to retrieve information for.
          required: true
          schema:
            type: string
      responses:
        '200':
          description: File or directory information retrieved successfully.
          content:
            application/json:
              schema:
                oneOf:
                  - title: FileDetails
                    $ref: '#/components/schemas/FileDetails'
                  - title: DirectoryDetails
                    $ref: '#/components/schemas/DirectoryDetails'
        '404':
          description: File or directory not found on specified path.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    post:
      tags:
        - Files
      summary: Create a new file or directory
      description: Create a an empty file or directory in the specified parent directory.
      operationId: CreateFile
      parameters:
        - name: path
          in: path
          description: The path of the parent directory.
          required: true
          schema:
            type: string
      requestBody:
        description: The request containing the details of the new item to create.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateFileRequest'
        required: true
      responses:
        '201':
          description: Item created successfully.
          content:
            application/json:
              schema:
                oneOf:
                  - title: DirectoryDetails
                    $ref: '#/components/schemas/DirectoryDetails'
                  - title: FileDetails
                    $ref: '#/components/schemas/FileDetails'
        '400':
          description: Item already exists.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: One or more validation errors occured.
                status: 400
                detail: string
                errors:
                  field:string:
                    - error:string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '404':
          description: Parent directory not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    put:
      tags:
        - Files
      summary: Upload a file
      description: 'Upload a file to the specified directory. If file already exists, it will be overwritten.'
      operationId: UploadFile
      parameters:
        - name: path
          in: path
          description: The path of the directory to upload the file to.
          required: true
          schema:
            type: string
      requestBody:
        content:
          multipart/form-data:
            schema:
              required:
                - file
              type: object
              properties:
                file:
                  $ref: '#/components/schemas/IFormFile'
        required: true
      responses:
        '201':
          description: File uploaded successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileDetails'
        '404':
          description: Directory not found.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    patch:
      tags:
        - Files
      summary: Update a file or directory
      description: 'Move or rename a file or directory on the specified path, or update text file''s content.'
      operationId: UpdateFile
      parameters:
        - name: path
          in: path
          description: The path of the file or directory to update.
          required: true
          schema:
            type: string
      requestBody:
        description: The request containing the update information.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateFileRequest'
        required: true
      responses:
        '201':
          description: File or directory moved successfully.
          content:
            application/json:
              schema:
                oneOf:
                  - title: FileDetails
                    $ref: '#/components/schemas/FileDetails'
                  - title: DirectoryDetails
                    $ref: '#/components/schemas/DirectoryDetails'
        '200':
          description: File's content updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileDetails'
        '404':
          description: File or directory not found on specified path.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '400':
          description: One or more validation errors occurred.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ValidationProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: One or more validation errors occured.
                status: 400
                detail: string
                errors:
                  field:string:
                    - error:string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
    delete:
      tags:
        - Files
      summary: Delete a file or a directory
      description: Delete a file or a directory on specified path.
      operationId: DeleteFile
      parameters:
        - name: path
          in: path
          description: The path of the file or directory to delete.
          required: true
          schema:
            type: string
      responses:
        '204':
          description: File or directory deleted successfully.
        '404':
          description: File or directory not found on specified path.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: Not Found
                status: 404
                detail: string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '400':
          description: Cannot delete root directory.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.5
                title: One or more validation errors occured.
                status: 400
                detail: string
                errors:
                  field:string:
                    - error:string
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '401':
          description: Authentication is required.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.2
                title: Unauthorized
                status: 401
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
        '403':
          description: Authenticated user is not allowed to access this resource.
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
              example:
                type: https://tools.ietf.org/html/rfc9110#section-15.5.4
                title: Forbidden
                status: 403
                traceId: 00-00000000000000000000000000000000-0000000000000000-00
      security:
        - Bearer: [ ]
components:
  schemas:
    CreateFileRequest:
      required:
        - name
        - type
      type: object
      properties:
        name:
          maxLength: 260
          minLength: 1
          pattern: '^[^/\\<>:"|?*\x00-\x1F]*[^/\\<>:"|?*\x00-\x1F\s.]$'
          type: string
          description: The name of the new item to create.
        type:
          description: The type of the new item to create.
          $ref: '#/components/schemas/ItemType'
      description: A request to create a new item.
      example:
        name: projects
    DirectoryDetails:
      required:
        - name
        - path
        - createdAt
        - updatedAt
      type: object
      properties:
        type:
          description: Gets the type of the directory child.
          $ref: '#/components/schemas/ItemType'
        name:
          type: string
          description: The name of the file.
        path:
          type: string
          description: The path of the file.
        createdAt:
          type: string
          description: The creation time of the file.
          format: date-time
        updatedAt:
          type: string
          description: The last update time of the file.
          format: date-time
        children:
          type:
            - 'null'
            - array
          description: The children of the directory. `null` if presented as a child.
      description: The details of a directory.
      example:
        name: example
        path: path/to/example
        createdAt: '2023-01-01T00:00:00Z'
        updatedAt: '2023-01-01T00:00:00Z'
        children: [ ]
        type: directory
    FileDetails:
      required:
        - name
        - path
        - createdAt
        - updatedAt
        - size
        - mime
      type: object
      properties:
        type:
          description: Gets the type of the directory child.
          $ref: '#/components/schemas/ItemType'
        name:
          type: string
          description: The name of the file.
        path:
          type: string
          description: The path of the file.
        createdAt:
          type: string
          description: The creation time of the file.
          format: date-time
        updatedAt:
          type: string
          description: The last update time of the file.
          format: date-time
        size:
          pattern: '^-?(?:0|[1-9]\d*)$'
          type:
            - integer
            - string
          description: The size of the file.
          format: int64
        mime:
          type: string
          description: The detected MIME-type of the file.
      description: The details of a file.
      example:
        name: example.txt
        path: path/to/example.txt
        size: 1024
        createdAt: '2023-01-01T00:00:00Z'
        updatedAt: '2023-01-01T00:00:00Z'
        type: file
    GetRuntimeInfoResponse:
      required:
        - enableOpenApi
        - isAuthenticated
        - shortenerHost
        - shortenerPrefix
        - caseInsensitiveSlugs
        - defaultSlugLength
        - filesHost
        - filesPrefix
        - appHost
        - appPrefix
        - usePasswordAuth
        - maxFileSize
      type: object
      properties:
        enableOpenApi:
          type: boolean
          description: Indicates whether OpenAPI is enabled.
        isAuthenticated:
          type: boolean
          description: Indicates whether the user is authenticated.
        shortenerHost:
          type: string
          description: The host of the shortener service.
        shortenerPrefix:
          type: string
          description: The prefix of the shortener service.
        caseInsensitiveSlugs:
          type: boolean
          description: Indicates whether short URL slugs are case-insensitive.
        defaultSlugLength:
          pattern: '^-?(?:0|[1-9]\d*)$'
          type:
            - integer
            - string
          description: Default number of characters for a randomized short URL slug.
          format: int32
        filesHost:
          type: string
          description: The host of the files service.
        filesPrefix:
          type: string
          description: The prefix of the files service.
        appHost:
          type: string
          description: The host of the main application.
        appPrefix:
          type: string
          description: The prefix of the main application.
        usePasswordAuth:
          type: boolean
          description: Indicates whther the app uses password authentication.
        maxFileSize:
          pattern: '^-?(?:0|[1-9]\d*)$'
          type:
            - integer
            - string
          description: Maximum file size for uploading in bytes.
          format: int32
      description: A response containing runtime information about the application.
    GetUserResponse:
      required:
        - subject
        - displayName
        - email
        - idpAvatar
      type: object
      properties:
        subject:
          type: string
          description: The subject of the user.
        displayName:
          type:
            - 'null'
            - string
          description: The display name of the user.
        email:
          type:
            - 'null'
            - string
          description: The email of the user.
        idpAvatar:
          type:
            - 'null'
            - string
          description: The avatar of the user from the identity provider.
          format: uri
      description: A response containing user information.
    HealthResponse:
      required:
        - status
      type: object
      properties:
        status:
          description: The health status of the application.
          $ref: '#/components/schemas/HealthStatus'
      description: A response containing the health status of the application.
      example:
        status: healthy
    HealthStatus:
      enum:
        - unhealthy
        - degraded
        - healthy
    IFormFile:
      type: string
      format: binary
    ItemType:
      enum:
        - file
        - directory
      description: A type of a filesystem item.
    LoginRequest:
      required:
        - username
        - password
      type: object
      properties:
        username:
          type: string
          description: Username.
        password:
          type: string
          description: Plaintext password.
      description: Password login request body.
      example:
        username: user
        password: qwerty123
    ProblemDetails:
      type: object
      properties:
        type:
          type:
            - 'null'
            - string
        title:
          type:
            - 'null'
            - string
        status:
          pattern: '^-?(?:0|[1-9]\d*)$'
          type:
            - 'null'
            - integer
            - string
          format: int32
        detail:
          type:
            - 'null'
            - string
        instance:
          type:
            - 'null'
            - string
    ShortLink:
      type: object
      properties:
        slug:
          pattern: '^[a-zA-Z0-9-_.]+$'
          type: string
          description: The slug of the short link.
        redirectUrl:
          type: string
          description: The URL to redirect to.
          format: uri
        forwardQuery:
          type: boolean
          description: Whether to forward the query string from the short link to the redirect URL.
        isEnabled:
          type: boolean
          description: Whether the short link is enabled.
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: The tags associated with the short link.
        createdAt:
          type: string
          description: The date and time when the short link was created.
          format: date-time
        updatedAt:
          type: string
          description: The date and time when the short link was last updated.
          format: date-time
        visits:
          pattern: '^-?(?:0|[1-9]\d*)$'
          type:
            - integer
            - string
          description: Number of times the URL was visited.
          format: int32
      description: A short link in the system.
      example:
        slug: my-link
        redirectUrl: https://example.com
        forwardQuery: false
        isEnabled: true
        tags: [ ]
        createdAt: '2024-01-01T00:00:00Z'
        updatedAt: '2024-01-01T00:00:00Z'
        visits: 15
    Tag:
      type: object
      properties:
        id:
          pattern: '^-?(?:0|[1-9]\d*)$'
          type:
            - integer
            - string
          description: The ID of the tag.
          format: int32
        name:
          maxLength: 32
          minLength: 1
          type: string
          description: The name of the tag.
        color:
          pattern: '^#[0-9a-fA-F]{6}$'
          type: string
          description: The color of the tag as a hexadecimal string.
      description: A tag in the system.
      example:
        id: 1
        name: My tag
        color: '#2596be'
    UpdateFileRequest:
      required:
        - destination
        - content
      type: object
      properties:
        destination:
          pattern: '^[^\\<>:"|?*\x00-\x1F]*[^/\\<>:"|?*\x00-\x1F\s.]$'
          type:
            - 'null'
            - string
          description: The destination path of the file or directory to update.
        content:
          type:
            - 'null'
            - string
          description: The content to update the file with.
      description: A request to update a file or directory.
      example:
        content: 'Hello, World!'
    UpdateLinkRequest:
      required:
        - slug
        - redirectUrl
        - forwardQuery
        - isEnabled
        - resetVisits
        - tags
      type: object
      properties:
        slug:
          pattern: '^[a-zA-Z0-9-_.]+$'
          type: string
          description: The slug of the short link.
        redirectUrl:
          type: string
          description: The URL to redirect to.
          format: uri
        forwardQuery:
          type: boolean
          description: Whether to forward the query string from the short link to the redirect URL.
        isEnabled:
          type: boolean
          description: Whether the short link is enabled.
        resetVisits:
          type: boolean
          description: Whether the visits coutner should be reset to 0.
        tags:
          type: array
          items:
            $ref: '#/components/schemas/Tag'
          description: The tags associated with the short link.
      description: Request model for updating or creating a short link.
    UpdateTagRequest:
      required:
        - name
        - color
      type: object
      properties:
        name:
          maxLength: 32
          minLength: 1
          type: string
          description: The name of the tag.
        color:
          pattern: '^#[0-9a-fA-F]{6}$'
          type: string
          description: The color of the tag in hex.
      description: A request to create or update a tag.
      example:
        name: My tag
        color: '#2596be'
    ValidationProblemDetails:
      type: object
      properties:
        type:
          type:
            - 'null'
            - string
        title:
          type:
            - 'null'
            - string
        status:
          pattern: '^-?(?:0|[1-9]\d*)$'
          type:
            - 'null'
            - integer
            - string
          format: int32
        detail:
          type:
            - 'null'
            - string
        instance:
          type:
            - 'null'
            - string
        errors:
          type: object
          additionalProperties:
            type: array
            items:
              type: string
  securitySchemes:
    Bearer:
      type: http
      description: Enter a JWT bearer token.
      scheme: bearer
      bearerFormat: JWT
tags:
  - name: Tags
    description: Manage tags
  - name: Files
    description: Manage static files
  - name: Links
    description: Manage short links
  - name: Public
    description: Public endpoints
  - name: Auth
    description: Authentication-related endpoints